- name: Install development tools and libraries
  hosts: all
  become: yes
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install necessary packages for GUI and other tools
      apt:
        name:
          - wget
          - python3.8
          - python3-pip
          - libgl1-mesa-glx
          - libqt5widgets5
        state: present

    - name: Upgrade pip and setuptools
      pip:
        name:
          - pip
          - setuptools
        state: latest
        executable: pip3

    - name: Install Conda via pip
      pip:
        name: conda
        state: present
        executable: pip3

    - name: Install pyqt5 separately
      pip:
        name: pyqt5==5.15.6
        state: present
        executable: pip3

    - name: Install Spyder 3.2.6
      pip:
        name: spyder==3.2.6
        state: present
        executable: pip3

    - name: Install paho-mqtt 1.5.0
      pip:
        name: paho-mqtt==1.5.0
        state: present
        executable: pip3

    - name: Install mosquitto
      apt:
        name: mosquitto
        state: present

    - name: Install hdf5 (via python-h5py)
      apt:
        name: python3-h5py
        state: present

    - name: Install pyserial
      pip:
        name: pyserial
        state: present
        executable: pip3

    - name: Install numpy
      pip:
        name: numpy
        state: present
        executable: pip3
