---
- name: Gather and print OS and Apache info
  hosts: all
  become: yes  # Ensure you have sudo privileges if needed
  tasks:
    - name: Gather OS information
      ansible.builtin.command: uname -a
      register: os_info

    - name: Print OS information
      ansible.builtin.debug:
        msg: "Operating System Info: {{ os_info.stdout }}"

    - name: Gather Apache version
      ansible.builtin.command: apache2 -v
      register: apache_info
      ignore_errors: yes  # Ignore errors if Apache is not installed

    - name: Print Apache version
      ansible.builtin.debug:
        msg: "Apache Info: {{ apache_info.stdout }}"
      when: apache_info.rc == 0

    - name: Gather Apache version (alternative path)
      ansible.builtin.command: httpd -v
      register: apache_info_alt
      ignore_errors: yes

    - name: Print Apache version (alternative path)
      ansible.builtin.debug:
        msg: "Apache Info: {{ apache_info_alt.stdout }}"
      when: apache_info_alt.rc == 0
