- name: Install Node.js
  hosts: all
  become: yes  # Ensure you have sudo privileges if needed
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install npm (optional, but often needed with Node.js)
      apt:
        name: npm
        state: present

    - name: Verify Node.js installation
      command: node -v
      register: node_version

    - name: Display Node.js version
      debug:
        msg: "Node.js version installed: {{ node_version.stdout }}"
