---
name: Install Node.js
  hosts: all
  become: yes

  tasks:
    - name: Add NodeSource repository
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add NodeSource Node.js 14.x repo
      apt_repository:
        repo: deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main
        state: present
        update_cache: yes

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Verify Node.js installation
      command: node -v
      register: node_version

    - name: Display Node.js version
      debug:
        msg: "Node.js version installed: {{ node_version.stdout }}"
