# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set environment variable for border color
ENV CSVSERVER_BORDER=Orange

# Set working directory
WORKDIR /app

# Copy application files and input file to the container
COPY app.py inputFile /app
# Install Flask and other dependencies
RUN pip install Flask

# Expose the port the application will run on
EXPOSE 9393

# Run the application
CMD ["python", "app.py"]

