version: '3.8'

services:
  csvserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9393:9393"
    env_file:
      - csvserver.env

  prometheus:
    image: prom/prometheus:v2.45.2
    ports:
      - "9090:9090"
    volumes:
      - /home/ec2-user/atul/solution/prometheus:/etc/prometheus/:Z

